FROM microsoft/aspnetcore:1.0.1
ENTRYPOINT ["dotnet", "AspnetCoreWebsite1.dll"]
WORKDIR /app
ENV ASPNETCORE_URLS http://+:5000
ENV OS_TYPE Linux
EXPOSE 5000
COPY bin/Debug/netcoreapp1.0/publish .
